P8105 Data Science I Homework 1
================
Olivia Wang (hw2852)
2022-09-17

# Problem 1

## 1.1 Loading & Summarizing the `Penguins` Dataset

First, let us load the `penguins` dataset.

``` r
data("penguins", package = "palmerpenguins")
```

Next, let us generate a summary of the `penguins` dataset, as well as
determine the number of rows and columns in the dataset.

``` r
summary(penguins)
```

    ##       species          island    bill_length_mm  bill_depth_mm  
    ##  Adelie   :152   Biscoe   :168   Min.   :32.10   Min.   :13.10  
    ##  Chinstrap: 68   Dream    :124   1st Qu.:39.23   1st Qu.:15.60  
    ##  Gentoo   :124   Torgersen: 52   Median :44.45   Median :17.30  
    ##                                  Mean   :43.92   Mean   :17.15  
    ##                                  3rd Qu.:48.50   3rd Qu.:18.70  
    ##                                  Max.   :59.60   Max.   :21.50  
    ##                                  NA's   :2       NA's   :2      
    ##  flipper_length_mm  body_mass_g       sex           year     
    ##  Min.   :172.0     Min.   :2700   female:165   Min.   :2007  
    ##  1st Qu.:190.0     1st Qu.:3550   male  :168   1st Qu.:2007  
    ##  Median :197.0     Median :4050   NA's  : 11   Median :2008  
    ##  Mean   :200.9     Mean   :4202                Mean   :2008  
    ##  3rd Qu.:213.0     3rd Qu.:4750                3rd Qu.:2009  
    ##  Max.   :231.0     Max.   :6300                Max.   :2009  
    ##  NA's   :2         NA's   :2

``` r
nrow(penguins)
```

    ## [1] 344

``` r
ncol(penguins)
```

    ## [1] 8

Dataset `penguins` has **344 rows** and **8 columns**. The 8 rows each
represent the following variables:

1.  Species: Adelie, Chinstrap, Gentoo
2.  Island: Biscoe, Dream, Torgersen
3.  Bill length in mm: 32.10 to 59.60
4.  Bill depth in mm: 13.10 to 21.50
5.  Flipper length in mm: 172.0 to 231.0
6.  Body mass in g: 2700 to 6300
7.  Sex: Female, Male
8.  Year: 2007, 2008, 2009

Based on the summary of the `penguins` dataset, we can see that the mean
flipper length is **200.9mm**.

## 1.2 Scatterplotting Flipper Length vs. Bill Length

Let us generate a scatterplot, plotting flipper length vs. bill length,
both measured in mm, using `ggplot`. In order to use the `ggplot`
function, let us first load the `tidyverse` library.

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
    ## ✔ ggplot2 3.3.6      ✔ purrr   0.3.4 
    ## ✔ tibble  3.1.8      ✔ dplyr   1.0.10
    ## ✔ tidyr   1.2.0      ✔ stringr 1.4.1 
    ## ✔ readr   2.1.2      ✔ forcats 0.5.2 
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

``` r
ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species)) + geom_point(na.rm = TRUE)
```

![](p8105_hw1_hw2852_files/figure-gfm/unnamed-chunk-3-1.png)<!-- -->

We can now export the scatterplot generated above to the project
directory using the `ggsave` function.

``` r
ggsave("penguins_flipper_vs_bill_scatterplot.pdf")
```

    ## Saving 7 x 5 in image

# Problem 2

## 2.1 Creating a Dataframe

Let us create a dataframe comprised of:

-   A random sample of size 10 from a standard Normal distribution;
-   A logical vector indicating whether elements of the sample are
    greater than 0;
-   A character vector of length 10; and
-   A factor vector of length 10, with 3 different factor “levels”.

``` r
problem2_df = 
  tibble(
    var_numeric = rnorm(n = 10, mean = 0, sd = 1),  
    var_logic = var_numeric > 0, 
    var_character = c("cat", "dog", "goat", "cow", "elephant", "sheep", "horse", "koala", "pig", "flamingo"), 
    var_factor = factor(c("high", "medium", "low", "low", "high", "low", "medium", "high", "low", "medium"))
    )
```

## 2.2 Taking the Means of Variables in a Dataframe

We can now take the mean of each variable created in the `problem2`
dataframe.

``` r
mean(pull(.data = problem2_df, var = var_numeric))
```

    ## [1] -0.4688849

``` r
mean(pull(.data = problem2_df, var = var_logic))
```

    ## [1] 0.4

``` r
mean(pull(.data = problem2_df, var = var_character))
```

    ## Warning in mean.default(pull(.data = problem2_df, var = var_character)):
    ## argument is not numeric or logical: returning NA

    ## [1] NA

``` r
mean(pull(.data = problem2_df, var = var_factor))
```

    ## Warning in mean.default(pull(.data = problem2_df, var = var_factor)): argument
    ## is not numeric or logical: returning NA

    ## [1] NA

Using the code above, we are able to generate the means of the numeric
and logic variables, but not those of the character or factor variables
(output: NA). At the time the code above was run, the mean of the
numeric variables was about 0.36 and that of the logic variables was
0.4.

## 2.3 Understanding How R Treats Different Variable Types

Before delving into possible explanations of why some means were able to
be generated while others were not, let us apply the `as.numeric`
function to attempt to convert the logical, character and factor
variables to numeric variables.

``` r
as.numeric(pull(.data = problem2_df, var = var_logic))
as.numeric(pull(.data = problem2_df, var = var_character))
as.numeric(pull(.data = problem2_df, var = var_factor))
```

Applying the `as.numeric` function converts the logical variable to a
binary output of 0 and 1, and converts the factor variable to 1’s, 2’s
and 3’s, each representing a different level of the factor variable;
however, the character variable was not able to be converted to a
numeric variable (output: NA). These results can both explain the
outputs generated when the means of each variable in the `problem2`
dataframe were taken earlier in Section 2.2, as well as how different
variables are treated and can be manipulated in R.

The binary output of 0 and 1 generated when the logical variable is
converted to a numerical variable is consistent with the specific
meaning that `TRUE` and `FALSE` have as reserved words in the R
language, denoting logical constants. While `TRUE` and `FALSE` in R do
hold the same meaning as they do in the English language, they also hold
the values of `TRUE` = 1 and `FALSE` = 0. As such, considering R will do
its best to carry out any function that it is told to do so, the mean of
the logical variable generated in Section 2.2 is simply the means of the
1’s and 0’s that correspond to `TRUE` and `FALSE`. This also explains
why the logical variable can be successfully converted to a numeric
variable upon applying the `as.numeric` function.

Recall in Section 2.2 that the mean of the factor variable was unable to
be generated. This is because, unlike the `TRUE` and `FALSE` of the
logic variable, `high`, `medium` and `low` are not specially reserved
words in the R language that carry additional meaning, or hold specific
values. As a result, the mean of the factor variable as a character
variable cannot be generated. After applying the `as.numeric` function,
the factor variable was successfully converted to a numeric variable,
taking on values of 1, 2 or 3. This demonstrates that while common
character variables cannot generate a mean nor be converted to numeric
variables, factor variable that have distinct levels and inherent order
are exceptions. In other words, *categorical ordinal* variables can be
converted to numerical variable, while *categorical nominal* variables
cannot. This is also consistent with the results generated when
attempting to take the mean of the character variable, and converting
the character variable to a numerical variable. In both cases, the
output generated was NA, since the character variable is categorical
nominal.
